# Use official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /backend

# Copy entire project into the container

COPY requirements.txt requirements.txt

#COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt && sleep 2

# Expose Flask port
EXPOSE 5001

# Start the Flask server
CMD ["python3", "run.py"]
