services:

  frontend:
    build:
      context: ./01-frontend
      dockerfile: Dockerfile.apache
    container_name: apache-frontend
    ports:
      - "8080:80"
    volumes:
      - ./01-frontend/apache/custom-conf.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      - app-network


  backend:
    build:
      context: ./02-backend
      dockerfile: Dockerfile.flask
    container_name: flask-backend
    ports:
      - "5001:5001"
    volumes:
      - ./02-backend/api/app.py:/app/app.py
    depends_on:
      - db
    networks:
      - app-network

  db:
    build:
      context: ./03-db
      dockerfile: Dockerfile.mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./03-db/mongo-init:/docker-entrypoint-initdb.d:ro
    env_file:
      - ./03-db/.env
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
